### ISSUE TITLE
Screen capture sources should be optional, since it requires various libX11 libraries on linux builds

### ISSUE THREAD

**Issue by Otterverse** [edaniels/gostream#3]
I'm working on packaging core, and noticed that it requires 7 libraries due to the inclusion of X11. Finally traced it here.

The "screen" package imported on the line linked below requires several X11 libraries, not always available (or desired) on headless systems. It would be ideal if screen capture support was optional so this could be avoided when not needed (such as our use in Core.)
https://github.com/edaniels/gostream/blob/e22ad4040f848e95321fe163cbbd6695594e4a90/media/query.go#L18

I verified that removing this one line removes those 7 deps, and core still passes all tests. Not sure what that might break for other users of this library though.

**Comment by edaniels** [comment]
@Otterverse, I moved it to the sample command instead since it isn't strictly necessary, especially with it pulling in a lot that many use cases won't require :).

Addressed in 9f921356bc09856edfea63536b98c63c4a235ad8. Can you close it once you confirm the libraries are not being required via https://github.com/viamrobotics/core builds?

**Comment by Otterverse** [comment]
Confirmed, X11 is no longer getting linked.
